// <auto-generated />
namespace Bookmarks_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class useridadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useridadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201508032252438_useridadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
